### ISSUE TITLE
Intradel

### ISSUE THREAD

**Issue by vegetrunks69** [thomasgermain/intradel-integration#2]
Bonjour, 
Merci pour votre « intradel » super pour le suivis

par contre ce jour celui-ci ne fonctionne plus. Allez continuer ?
d'avance merci

**Comment by thomasgermain** [comment]
Bonjour, 

L'intégration fonctionne toujours.

L'intégration "lit" la page web d'intradel pour connaître les levées et le poids, mais pour le moment, seul les info des recyparc sont disponibles, donc l'intégration retourne "unavailable" pour les autres entity.

Je suppose qu'intradel donnera les informations à nouveau peu après votre première levée. Pas optimal, mais je ne vois pas d'autre solution pour le moment 🫤

**Comment by vegetrunks69** [comment]
Bonjour,

Merci pour votre réponse rapide 😉
D’accord, je comprend mieux. Je ressaierai donc plus tard de la réinstaller vu que les sensor orga et recu ne sont plus dispos pour le moment!

Bon travail! Super pour le suivis !

Bonne continuation et meilleur vœux


Le 2 janv. 2024 à 16:44, Thomas Germain ***@***.***> a écrit :

﻿

Bonjour,

L'intégration fonctionne toujours.

L'intégration "lit" la page web d'intradel pour connaître les levées et le poids, mais pour le moment, seul les info des recyparc sont disponibles, donc l'intégration retourne "unavailable" pour les autres entity.

Je suppose qu'intradel donnera les informations à nouveau peu après votre première levée. Pas optimal, mais je ne vois pas d'autre solution pour le moment 🫤

**Comment by vegetrunks69** [comment]
Bonjour, 
Je confirme votre réponse. 
celle ci fonctionne à nouveau lors de la première levée.
Bonne journée
